apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openam
spec:
  replicas: 1
  template:
    metadata:
      labels:
         name: openam
         site: site1
    spec:
      containers:
      - name: openam
        image: forgerock/openam:template
        imagePullPolicy: Always
        ports:
          - name: openam
            containerPort: 8080
